export const sampleProducts = [
  {
    id: "1",
    name: "Oak Hardwood Flooring",
    category: "Hardwood",
    price: 89.99,
    salePrice: 74.99,
    description: "Premium oak hardwood flooring with natural grain patterns",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
    brand: "FlooringHause Premium",
    material: "Oak",
    stockStatus: "In Stock",
    sqftPerBox: 24.5,
    thickness: "3/4 inch",
    warranty: "25 years"
  },
  {
    id: "2",
    name: "Marble Mosaic Tiles",
    category: "Tile",
    price: 129.99,
    description: "Elegant marble mosaic tiles for luxury spaces",
    imageUrl: "https://images.unsplash.com/photo-1564540579594-0930edb6de43?w=600",
    brand: "TruSa Collection",
    material: "Marble",
    stockStatus: "In Stock",
    sqftPerBox: 10,
    thickness: "3/8 inch",
    warranty: "Lifetime"
  },
  {
    id: "3",
    name: "Luxury Vinyl Plank",
    category: "Vinyl",
    price: 45.99,
    salePrice: 39.99,
    description: "Waterproof luxury vinyl plank with wood-look design",
    imageUrl: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600",
    brand: "FlooringHause",
    material: "Vinyl",
    stockStatus: "In Stock",
    sqftPerBox: 20,
    thickness: "5mm",
    warranty: "15 years"
  },
  {
    id: "4",
    name: "Plush Carpet",
    category: "Carpet",
    price: 34.99,
    description: "Soft and luxurious plush carpet for bedrooms",
    imageUrl: "https://images.unsplash.com/photo-1556228841-a3c527ebefe5?w=600",
    brand: "FlooringHause Comfort",
    material: "Nylon",
    stockStatus: "In Stock",
    sqftPerBox: 30,
    thickness: "1/2 inch",
    warranty: "10 years"
  },
  {
    id: "5",
    name: "Walnut Laminate",
    category: "Laminate",
    price: 29.99,
    description: "Durable walnut laminate flooring with authentic wood texture",
    imageUrl: "https://images.unsplash.com/photo-1560185007-cde436f6a4c0?w=600",
    brand: "FlooringHause",
    material: "Laminate",
    stockStatus: "Low Stock",
    sqftPerBox: 18.5,
    thickness: "12mm",
    warranty: "20 years"
  },
  {
    id: "6",
    name: "Porcelain Tiles",
    category: "Tile",
    price: 65.99,
    description: "High-quality porcelain tiles with marble finish",
    imageUrl: "https://images.unsplash.com/photo-1565183997392-2f6f122e5912?w=600",
    brand: "FlooringHause Elite",
    material: "Porcelain",
    stockStatus: "In Stock",
    sqftPerBox: 15,
    thickness: "1/2 inch",
    warranty: "Lifetime"
  },
  {
    id: "7",
    name: "Bamboo Flooring",
    category: "Hardwood",
    price: 79.99,
    salePrice: 69.99,
    description: "Eco-friendly bamboo flooring with natural beauty",
    imageUrl: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=600",
    brand: "FlooringHause Green",
    material: "Bamboo",
    stockStatus: "In Stock",
    sqftPerBox: 22,
    thickness: "5/8 inch",
    warranty: "25 years"
  },
  {
    id: "8",
    name: "Gray Vinyl Tiles",
    category: "Vinyl",
    price: 55.99,
    description: "Modern gray vinyl tiles with stone texture",
    imageUrl: "https://images.unsplash.com/photo-1615873968403-89e068629265?w=600",
    brand: "FlooringHause",
    material: "Vinyl",
    stockStatus: "Out of Stock",
    sqftPerBox: 25,
    thickness: "4mm",
    warranty: "15 years"
  }
];